name: Publish

on:
  push:
    branches: master
    paths:
      - '.github/workflows/publish.yml'
      - '**.cs'
      - '**.csproj'

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: |
            8.0.x
            10.0.x

      - name: Test
        run: dotnet test src/Converter.MarkdownToBBCodeNM.sln --configuration Release
        shell: pwsh

      - name: Pack
        run: |
          dotnet pack src/Converter.MarkdownToBBCodeNM.Tool/Converter.MarkdownToBBCodeNM.Tool.csproj --configuration Release -o ./packages;
          dotnet pack src/Converter.MarkdownToBBCodeSteam.Tool/Converter.MarkdownToBBCodeSteam.Tool.csproj --configuration Release -o ./packages;
        shell: pwsh

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: ./packages/

      - name: NuGet login (trusted publishing)
        uses: NuGet/login@v1
        id: nuget-login
        with:
          user: Aragas

      - name: Push to NuGet
        if: github.ref == 'refs/heads/master'
        run: dotnet nuget push "./packages/*.nupkg" -k ${{ steps.nuget-login.outputs.NUGET_API_KEY }} -s https://www.nuget.org
        shell: pwsh
  
      - name: Push to GPR
        if: github.ref == 'refs/heads/master'
        run: dotnet nuget push "./packages/*.nupkg" -k ${{secrets.GITHUB_TOKEN}} -s https://nuget.pkg.github.com/BUTR/index.json --skip-duplicate
        shell: pwsh
